version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - gocognit
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - mnd
    - nestif
    - nilerr
    - noctx
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        main:
          files:
            - "$all"
          allow:
            - encoding/json
            - regexp
            - slices
            - strings
            - github.com/newrelic/nri-kube-events/pkg/common
            - github.com/sirupsen/logrus
            - k8s.io/api/core/v1
            - k8s.io/apimachinery/pkg/apis/meta/v1
            - k8s.io/apimachinery/pkg/runtime
            - k8s.io/apimachinery/pkg/runtime/schema
            - k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
            - k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset
            - k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions
            - k8s.io/client-go/discovery
            - k8s.io/client-go/dynamic
            - k8s.io/client-go/dynamic/dynamicinformer
            - k8s.io/client-go/rest
            - k8s.io/cli-runtime/pkg/printers
            - k8s.io/client-go/kubernetes/scheme
            - k8s.io/kube-aggregator/pkg/apis/apiregistration/v1
    dupl:
      threshold: 100
    gocyclo:
      min-complexity: 20
    govet:
      enable:
        - shadow
        - fieldalignment
    misspell:
      locale: US
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/newrelic/nri-kube-events
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
