version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - gocognit
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - mnd
    - nestif
    - nilerr
    - noctx
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 100
    gocyclo:
      min-complexity: 20
    govet:
      enable:
        - shadow
        - fieldalignment
    misspell:
      locale: US
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/newrelic/nri-kube-events
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
