linters:
  disable-all: true
  enable:
    - goimports
    - golint
    - govet
    - unused
    - goconst
    - errcheck
  fast: true

# all available settings of specific linters
linters-settings:
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0.3

issues:
  exclude-use-default: false

misspell:
    locale: US

lll:
  line-length: 100
