apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: nri-kube-events
build:
  artifacts:
  - image: newrelic/nri-kube-events
    context: .
    custom:
      buildCommand: ./skaffold_build.sh
      dependencies:
        paths:
        - "**/*.go"
        - go.mod
        - skaffold_build.sh
  tagPolicy:
    sha256: {}
manifests:
  rawYaml:
  - deploy/local.yaml
deploy:
  kubectl: {}
