apiVersion: v2
name: nri-kube-events
description: A Helm chart to deploy the New Relic Kube Events router
home: https://docs.newrelic.com/docs/integrations/kubernetes-integration/kubernetes-events/install-kubernetes-events-integration
icon: https://newrelic.com/themes/custom/curio/assets/mediakit/NR_logo_Horizontal.svg
sources:
  - https://github.com/newrelic/nri-kube-events/
  - https://github.com/newrelic/nri-kube-events/tree/master/charts/newrelic-infrastructure

version: 2.2.2
appVersion: 1.8.0

dependencies:
  - name: common-library
    version: 1.0.2
    repository: "https://helm-charts.newrelic.com"

maintainers:
  - name: Alvaro Cabanas
    url: https://github.com/alvarocabanas
  - name: Carlos Castro
    url: https://github.com/carlossscastro
  - name: Christian Felipe
    url: https://github.com/sigilioso
  - name: Guillermo Sanchez
    url: https://github.com/gsanchezgavier
  - name: Juan Manuel Perez
    url: https://github.com/kang-makes
  - name: Marc Sanmiquel
    url: https://github.com/marcsanmi
  - name: Paolo Gallina
    url: https://github.com/paologallinaharbur
  - name: Roberto Santalla
    url: https://github.com/roobre

keywords:
  - infrastructure
  - newrelic
  - monitoring
