apiVersion: v2
description: A Helm chart to deploy the New Relic Kube Events
name: nri-kube-events
version: 1.15.0
appVersion: 1.8.0
engine: gotpl
home: https://docs.newrelic.com/docs/integrations/kubernetes-integration/kubernetes-events/install-kubernetes-events-integration
icon: https://newrelic.com/assets/newrelic/source/NewRelic-logo-square.svg

dependencies:
  - name: common-library
    version: 1.0.0
    repository: "https://helm-charts.newrelic.com"

maintainers:
  - name: alvarocabanas
  - name: carlossscastro
  - name: gsanchezgavier
  - name: kang-makes
  - name: marcsanmi
  - name: paologallinaharbur
  - name: roobre
  - name: sigilioso
keywords:
  - infrastructure
  - newrelic
  - monitoring
