apiVersion: v2
name: nri-kube-events
description: A Helm chart to deploy the New Relic Kube Events router
home: https://docs.newrelic.com/docs/integrations/kubernetes-integration/kubernetes-events/install-kubernetes-events-integration
icon: https://newrelic.com/themes/custom/curio/assets/mediakit/NR_logo_Horizontal.svg
sources:
  - https://github.com/newrelic/nri-kube-events/
  - https://github.com/newrelic/nri-kube-events/tree/main/charts/nri-kube-events
  - https://github.com/newrelic/infrastructure-agent/

version: 2.2.7
appVersion: 1.8.0

dependencies:
  - name: common-library
    version: 1.0.6
    repository: "https://helm-charts.newrelic.com"

maintainers:
  - name: alvarocabanas
    url: https://github.com/alvarocabanas
  - name: carlossscastro
    url: https://github.com/carlossscastro
  - name: sigilioso
    url: https://github.com/sigilioso
  - name: gsanchezgavier
    url: https://github.com/gsanchezgavier
  - name: kang-makes
    url: https://github.com/kang-makes
  - name: marcsanmi
    url: https://github.com/marcsanmi
  - name: paologallinaharbur
    url: https://github.com/paologallinaharbur
  - name: roobre
    url: https://github.com/roobre

keywords:
  - infrastructure
  - newrelic
  - monitoring
