global:
  licenseKey: 1234567890abcdef1234567890abcdef12345678
  cluster: test-cluster

sinks:
  # Enable the stdout sink to also see all events in the logs.
  stdout: true
  # The newRelicInfra sink sends all events to New relic.
  newRelicInfra: true
