global:
  licenseKey: 1234567890abcdef1234567890abcdef12345678
  cluster: test-cluster

sinks:
  # Enable the stdout sink to also see all events in the logs.
  stdout: true
  # The newRelicInfra sink sends all events to New relic.
  newRelicInfra: true

config:
  accountID: 111
  region: EU

rbac:
  create: true

runAsUser: 1000

serviceAccount:
  create: true

podAnnotations:
  annotation1: "annotation"

nodeSelector:
  kubernetes.io/os: linux

tolerations:
  - key: "key1"
    effect: "NoSchedule"
    operator: "Exists"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux

hostNetwork: true

image:
  kubeEvents:
    repository: e2e/nri-kube-events
    tag: test
    pullPolicy: IfNotPresent
