{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
{{ include "nri-kube-events.labels" . | indent 4 }}
  name: {{ template "nri-kube-events.fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "watch", "list"]
{{- end -}}
