{{- $licenseKey := include "nri-kube-events.licenseKey" . -}}
{{- if $licenseKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nri-kube-events.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "nri-kube-events.labels" . | indent 4 }}
type: Opaque
data:
  licenseKey: {{ $licenseKey | b64enc }}
{{- end }}
