{{- $licenseKey := include "newrelic.common.license._licenseKey" . -}}
{{- if $licenseKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "newrelic.common.naming.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "newrelic.common.labels" . | indent 4 }}
type: Opaque
data:
  licenseKey: {{ $licenseKey | b64enc }}
{{- end }}
