{{- if include "common.serviceAccount.create" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "common.labels" . | indent 4 }}
  name: {{ include "common.serviceAccount.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
{{ include "common.serviceAccount.annotations" | indent 4 }}
{{- end -}}
